import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { siteConfig } from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://taiwoolapade.vercel.app"),
  title: {
    default: siteConfig.name,
    template: "%s - Software Engineer",
  },
  description: "Generated by create next app",

  keywords: [
    "Next.js",
    "React",
    "TypeScript",
    "Software Engineer",
    "Taiwo Olapade",
    "Full Stack Developer",
    "Software Development",
    "React Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "Next.js Developer",
    "React Native Developer",
    "Web Development",
    "Software Architecture",
    "Cloud Computing",
    "DevOps",
    "Node.js",
    "Python",
    "Golang",
    "GraphQL",
    "REST API",
    "Websockets",
    "Serverless",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "ElasticSearch",
    "RabbitMQ",
    "InfluxDB",
    "Grafana",
    "Prometheus",
    "Alertmanager",
    "Nginx",
    "Apache",
    "Load Balancer",
  ],

  authors: [
    {
      name: "Taiwo Olapade",
      url: "https://taiwoolapade.vercel.app",
    },
  ],
  creator: "Taiwo Olapade",

  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    images: siteConfig.ogImage,
    siteName: siteConfig.name,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
